AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for React app hosted with S3 and CloudFront

Resources:
  # Our cloud resources will be defined here ...

Outputs:
  # Resource values we'd like to output  ...