version = 0.1
[default.deploy.parameters]
stack_name = "photo-app-react"
resolve_s3 = true
s3_prefix = "photo-app-react"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
